from GAME_INTRODUCTION import GAME_INTRODUCTION
from PROCESS_COMMAND import PROCESS_COMMAND
from CHEST import CHEST
import GAME_WORLD
from LOCATION import LOCATION

def GET_PLAYER_INPUT():
    return input("Enter your COMMAND: ")


def GAME():
    GAME_RUNNING = True
    PLAYER_POSITION = (0, 0)  # Starting position of the player
    LOCATION.ADD_ENTITY(GAME_WORLD.SMALL_ROOM1, CHEST)
    GAME_INTRODUCTION(PLAYER_POSITION)
    while GAME_RUNNING:
        COMMAND = GET_PLAYER_INPUT()
        GAME_RUNNING, PLAYER_POSITION = PROCESS_COMMAND(COMMAND, PLAYER_POSITION)

    print("GAME OVER.")
