import logging

from WORLD.GLOBAL import MOBS, INITIATIVE_MOBS, INITIATIVE_MOB_NAMES, GLOBAL_FLAGS
from WORLD.LOCATIONS.LOCATION_ID import LOCATION_ID
from ENTITIES.ITEMS.ARMOR.CHAIN_SHIRT import CHAIN_SHIRT
from ENTITIES.ITEMS.ARMOR.CHAIN_MAIL import CHAIN_MAIL
from ENTITIES.ITEMS.ARMOR.LEATHER_ARMOR import LEATHER_ARMOR
from ENTITIES.ITEMS.MELEE_WEAPONS.CLUB import CLUB
from ENTITIES.ITEMS.MELEE_WEAPONS.GREATCLUB import GREATCLUB
from ENTITIES.ITEMS.MELEE_WEAPONS.HANDAXE import HANDAXE
from ENTITIES.ITEMS.MELEE_WEAPONS.JAVELIN import JAVELIN
from ENTITIES.ITEMS.MELEE_WEAPONS.LONGSWORD import LONGSWORD
from ENTITIES.ITEMS.MELEE_WEAPONS.QUARTERSTAFF import QUARTERSTAFF
from ENTITIES.ITEMS.MELEE_WEAPONS.SCIMITAR import SCIMITAR
from ENTITIES.ITEMS.MELEE_WEAPONS.SHORTSWORD import SHORTSWORD
from ENTITIES.ITEMS.MELEE_WEAPONS.SPEAR import SPEAR
from ENTITIES.ITEMS.MELEE_WEAPONS.DAGGER import DAGGER
from ENTITIES.ITEMS.ARMOR.SHIELD import SHIELD

logging.basicConfig(level=logging.DEBUG, format='%(levelname)s: %(message)s')

LOOT = ["GOLD", SHIELD, CHAIN_MAIL, CHAIN_SHIRT, LEATHER_ARMOR, CLUB, GREATCLUB, HANDAXE, JAVELIN, LONGSWORD, QUARTERSTAFF, SCIMITAR, SHORTSWORD, SPEAR, DAGGER]


def INITIATIVE(PLAYER, LOCATION):
    DEBUG = GLOBAL_FLAGS["DEBUG"]
    _MOBS = []
    
    for MOB in MOBS:
        if MOB and (LOCATION_ID(*MOB.POSITION[0:2]) == LOCATION or MOB == PLAYER):
            _MOBS.append(MOB)
    
    _INITIATIVE_MOBS = sorted(_MOBS, key=lambda mob: mob.ROLL_INITIATIVE())

    INITIATIVE_MOBS.clear()
    INITIATIVE_MOB_NAMES.clear()

    for MOB in _INITIATIVE_MOBS:
        INITIATIVE_MOBS.append(MOB)
        INITIATIVE_MOB_NAMES.append(MOB.NAME)
    if DEBUG:
        logging.debug(INITIATIVE_MOB_NAMES)
    return INITIATIVE_MOBS


