from WORLD.LOCATION_ID import LOCATION_ID
from ENTITIES.MOBS.KAREN import KAREN
from LOGIC.MATH import RELATIVE_LOCATION

def GAME_DISPLAY(MOBS, TURN):
    print(f"\nTurn: {TURN}")
    for MOB in MOBS:
        if MOB.NAME == "YOU":
            CURRENT_LOCATION = LOCATION_ID(*MOB.POSITION).DESCRIPTION
            print(f"Health: {MOB.HEALTH}/{MOB.MAX_HEALTH}.\nLocation: {MOB.POSITION}\n{CURRENT_LOCATION}")
        elif LOCATION_ID(*MOB.POSITION) == LOCATION_ID(*MOBS[0].POSITION):
            MOB_INDEX = MOBS.index(MOB)
            X_DISTANCE, Z_DISTANCE, X_DIRECTION, Z_DIRECTION = RELATIVE_LOCATION(*MOBS[0].POSITION, *MOB.POSITION)
            print(f"{MOB.NAME} (ID: {MOB_INDEX}, HEALTH: {MOB.HEALTH}/{MOB.MAX_HEALTH}): {X_DISTANCE} feet {X_DIRECTION}, {Z_DISTANCE} feet {Z_DIRECTION}.")