from WORLD.LOCATIONS.LOCATION import LOCATION


class SMALL_ROOM(LOCATION):

    def __init__(self, X, Y, LEVEL, LOCAL_ITEMS=None, DOORS=None, START=False, VICTORY=False):
        super().__init__(X, Y, 6, 6, "SMALL ROOM", LEVEL, LOCAL_ITEMS=LOCAL_ITEMS, DOORS=DOORS, START=START, VICTORY=VICTORY)
