from ENTITIES.ITEMS.MELEE_WEAPONS.MELEE_WEAPON import MELEE_WEAPON

class GREATAXE(MELEE_WEAPON):

    def __init__(self, POSITION=None, PRICE=30):
        super().__init__((1, 12), "GREATAXE", 7, POSITION, PRICE, None, "HEAVY", "TWO-HANDED")
