from WORLD.LOCATION_ID import LOCATION_ID
from LOGIC.MATH import VECTOR_DIRECTION

def FOLLOW_PLAYER(PLAYER, MOB):
    if PLAYER.POSITION == MOB.POSITION:
        return False
    else:
        PLAYER_X, PLAYER_Y = PLAYER.POSITION
        MOB_X, MOB_Y = MOB.POSITION

        DX = PLAYER_X - MOB_X
        DY = PLAYER_Y - MOB_Y

        return VECTOR_DIRECTION(DX, DY)
